spring.application.name=game-store-api
spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.open-in-view=false

app.security.jwt.secret-base64=${JWT_SECRET_BASE64}
app.bootstrap.manager-email=${MANAGER_EMAIL}
app.bootstrap.manager-password=${MANAGER_PASSWORD}
